-- Create a table to track individual read events with timestamps
create table public.user_book_read_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  book_id integer not null,
  read_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index for faster queries
create index idx_user_book_read_history_user_book on public.user_book_read_history(user_id, book_id);
create index idx_user_book_read_history_read_at on public.user_book_read_history(read_at);

-- Set up Row Level Security (RLS)
alter table public.user_book_read_history enable row level security;

-- Create policies
create policy "Users can view their own read history"
  on public.user_book_read_history for select
  using (auth.uid() = user_id);

create policy "Users can insert their own read history"
  on public.user_book_read_history for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own read history"
  on public.user_book_read_history for delete
  using (auth.uid() = user_id);
