-- Create a table to track how many times a user has read a book
create table public.user_book_reads (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  book_id integer not null,
  read_count integer default 1,
  last_read_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, book_id)
);

-- Set up Row Level Security (RLS)
alter table public.user_book_reads enable row level security;

-- Create policies
create policy "Users can view their own book reads"
  on public.user_book_reads for select
  using (auth.uid() = user_id);

create policy "Users can insert their own book reads"
  on public.user_book_reads for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own book reads"
  on public.user_book_reads for update
  using (auth.uid() = user_id);
